# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from managementservice.api_helper import APIHelper


class TemplatesAndUserAuthorizationControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(TemplatesAndUserAuthorizationControllerTests, cls).setUpClass()
        cls.controller = cls.client.templates_and_user_authorization
        cls.response_catcher = cls.controller.http_call_back

    # Testcase for testing endpoint TemplateAccessibilityController_GetAllpublicPipelines
    def test_template_accessibility_controller_get_allpublic_pipelines(self):

        # Perform the API call through the SDK function
        self.controller.template_accessibility_controller_get_allpublic_pipelines()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Testcase for testing endpoint TemplateAccessibilityController_GetPipelinesDetails
    def test_template_accessibility_controller_get_pipelines_details(self):
        # Parameters for the API call
        ids = None

        # Perform the API call through the SDK function
        self.controller.template_accessibility_controller_get_pipelines_details(ids)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

