# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from managementservice.api_helper import APIHelper


class DocumentationControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(DocumentationControllerTests, cls).setUpClass()
        cls.controller = cls.client.documentation
        cls.response_catcher = cls.controller.http_call_back

    # Testcase for testing endpoint DocumentationController_getAllArticles
    def test_documentation_controller_get_all_articles(self):

        # Perform the API call through the SDK function
        self.controller.documentation_controller_get_all_articles()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

