# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AuthorizedUserDto(object):

    """Implementation of the 'AuthorizedUserDto' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        template_id (string): TODO: type description here.
        user_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "template_id": 'templateId',
        "user_id": 'userId'
    }

    def __init__(self,
                 id=None,
                 template_id=None,
                 user_id=None):
        """Constructor for the AuthorizedUserDto class"""

        # Initialize members of the class
        self.id = id 
        self.template_id = template_id 
        self.user_id = user_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else None
        template_id = dictionary.get("templateId") if dictionary.get("templateId") else None
        user_id = dictionary.get("userId") if dictionary.get("userId") else None
        # Return an object of this model
        return cls(id,
                   template_id,
                   user_id)
