# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from managementservice.api_helper import APIHelper


class CreateProjectMemberDto(object):

    """Implementation of the 'CreateProjectMemberDto' model.

    TODO: type model description here.

    Attributes:
        user_name (string): TODO: type description here.
        user_id (string): TODO: type description here.
        project_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_name": 'userName',
        "user_id": 'userId',
        "project_id": 'projectId'
    }

    _optionals = [
        'user_name',
        'user_id',
        'project_id',
    ]

    def __init__(self,
                 user_name=APIHelper.SKIP,
                 user_id=APIHelper.SKIP,
                 project_id=APIHelper.SKIP):
        """Constructor for the CreateProjectMemberDto class"""

        # Initialize members of the class
        if user_name is not APIHelper.SKIP:
            self.user_name = user_name 
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id 
        if project_id is not APIHelper.SKIP:
            self.project_id = project_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        user_name = dictionary.get("userName") if dictionary.get("userName") else APIHelper.SKIP
        user_id = dictionary.get("userId") if dictionary.get("userId") else APIHelper.SKIP
        project_id = dictionary.get("projectId") if dictionary.get("projectId") else APIHelper.SKIP
        # Return an object of this model
        return cls(user_name,
                   user_id,
                   project_id)
