# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PipelineDto(object):

    """Implementation of the 'PipelineDto' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        pipeline_id (string): TODO: type description here.
        project_id (string): TODO: type description here.
        owner_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "pipeline_id": 'pipelineId',
        "project_id": 'projectId',
        "owner_id": 'ownerId'
    }

    def __init__(self,
                 id=None,
                 pipeline_id=None,
                 project_id=None,
                 owner_id=None):
        """Constructor for the PipelineDto class"""

        # Initialize members of the class
        self.id = id 
        self.pipeline_id = pipeline_id 
        self.project_id = project_id 
        self.owner_id = owner_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else None
        pipeline_id = dictionary.get("pipelineId") if dictionary.get("pipelineId") else None
        project_id = dictionary.get("projectId") if dictionary.get("projectId") else None
        owner_id = dictionary.get("ownerId") if dictionary.get("ownerId") else None
        # Return an object of this model
        return cls(id,
                   pipeline_id,
                   project_id,
                   owner_id)
