# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TemplateDto(object):

    """Implementation of the 'TemplateDto' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        template_id (string): TODO: type description here.
        owner_id (string): TODO: type description here.
        accessibility (string): TODO: type description here.
        template_type (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "template_id": 'templateId',
        "owner_id": 'ownerId',
        "accessibility": 'accessibility',
        "template_type": 'templateType'
    }

    def __init__(self,
                 id=None,
                 template_id=None,
                 owner_id=None,
                 accessibility=None,
                 template_type=None):
        """Constructor for the TemplateDto class"""

        # Initialize members of the class
        self.id = id 
        self.template_id = template_id 
        self.owner_id = owner_id 
        self.accessibility = accessibility 
        self.template_type = template_type 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else None
        template_id = dictionary.get("templateId") if dictionary.get("templateId") else None
        owner_id = dictionary.get("ownerId") if dictionary.get("ownerId") else None
        accessibility = dictionary.get("accessibility") if dictionary.get("accessibility") else None
        template_type = dictionary.get("templateType") if dictionary.get("templateType") else None
        # Return an object of this model
        return cls(id,
                   template_id,
                   owner_id,
                   accessibility,
                   template_type)
