# -*- coding: utf-8 -*-

"""
managementservice

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from managementservice.api_helper import APIHelper


class UpdateProjectDto(object):

    """Implementation of the 'UpdateProjectDto' model.

    TODO: type model description here.

    Attributes:
        title (string): TODO: type description here.
        description (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "title": 'title',
        "description": 'description'
    }

    _optionals = [
        'title',
        'description',
    ]

    def __init__(self,
                 title=APIHelper.SKIP,
                 description=APIHelper.SKIP):
        """Constructor for the UpdateProjectDto class"""

        # Initialize members of the class
        if title is not APIHelper.SKIP:
            self.title = title 
        if description is not APIHelper.SKIP:
            self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        title = dictionary.get("title") if dictionary.get("title") else APIHelper.SKIP
        description = dictionary.get("description") if dictionary.get("description") else APIHelper.SKIP
        # Return an object of this model
        return cls(title,
                   description)
